# Generated by Django 5.0.6 on 2024-05-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_bus_facilities'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_seat_trip',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seat', 'trip')},
        ),
    ]
