# Generated by Django 5.0.6 on 2024-05-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_remove_ticket_unique_ticket_seat_trip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['seat']},
        ),
    ]
