# Generated by Django 5.0.6 on 2024-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(null=True, upload_to='???'),
        ),
    ]
