# Generated by Django 5.0.6 on 2024-05-16 16:11

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_bus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.bus_image_path),
        ),
    ]
